config/routes.rb
Rails.application.routes.draw do
  resources :folders

  resources :patients

  get 'pages/baa'
  get 'pages/index'

  devise_for :users
  resources :images
  resources :charges

  root 'patients#index'
  get 'pages/baa'

  match "patient/share" => "patient#share", via: [:get, :post]

end

app/models/image.rb
class Image < ActiveRecord::Base
require 'aws-sdk'


	has_attached_file :image_file, 
    :styles => {
      :thumb => "50x50#",
      :original => "1500x1500>"},
 url: "/dental-imager/images/:id/:style/:filename", path:"/dental-imager/images/:id/:style/:filename"
	# validates_attachment_file_name :image_file, matches: [/png\Z/, /jpeg\Z/, /tiff\Z/, /bmp\Z/, /jpg\Z/]
   validates_attachment_content_type :image_file, content_type: /\Aimage\/.*\Z/
   validates :image_file, :presence => true
  	#validates :patient_name, :presence => true
  	belongs_to :patient
  	# belongs_to :user

  before_create :add_token
		private
		def add_token
		  begin
		    self.token = SecureRandom.hex[0,10].upcase
		  end while self.class.exists?(token: token)
		end


end

app/models/patient.rb
class Patient < ActiveRecord::Base
has_many :images
accepts_nested_attributes_for :images#, reject_if: :all_blank, allow_destroy: true
belongs_to :user

  before_create :add_token
		private
		def add_token
		  begin
		    self.token = SecureRandom.hex[0,10].upcase
		  end while self.class.exists?(token: token)
		end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :confirmable

  has_many :images#, :through => :patients
  has_many :patients


  	validates :name, :presence => true
  	validates :telephone, :presence => true
  	validates :agreement, :presence => true, :on => :create

  after_create :send_sign_up_email

  def send_sign_up_email
	Usermailer.sign_up(id).deliver_later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	before_action :authenticate_user!, :except => [:show]

    before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
	    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :telephone, :referall, :agreement])
	    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :current_password, :telephone, :agreement])
    end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
def new
end

def create
	  # Amount in cents
	  token = params[:stripeToken]

	  customer = Stripe::Customer.create(
		  :source => token, # obtained from Stripe.js
		  :plan => "2495monthly",
		  :email => current_user.email,
		  #:coupon => current_user.referall
	  	)

	  current_user.subscribed = true
	  current_user.save!
	  
	  redirect_to root_path

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to charges_path
	end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user, :except => [:index, :new, :create, :update]
  # GET /images
  # GET /images.json
  def index

    @images = current_user.images.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])
    # @image = Image.find_by(token: params[:token], id: params[:id])
  end

  def share
  end

  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)


    respond_to do |format|
      if @image.save
        # ImagesMailer.email(@image).deliver_later
        format.html { redirect_to root_path, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:patient_name, :patient_id, :image_desc, :dob, :image_file, :user_name, :token, :user_id, :recipient)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def baa
  end

  def index

  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show]
  # GET /patients
  # GET /patients.json
  def index
     @patients = current_user.patients.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)

  end


  # GET /patients/1
  # GET /patients/1.json
  def show
    if user_signed_in?
    @patient = Patient.find(params[:id])
  else
    @patient = Patient.find_by(token: params[:token], id: params[:id])
    @images = @patient.images
  end
  end

  # GET /patients/new
  def new
    if current_user.created_at <= 1.week.ago && !current_user.subscribed
        redirect_to new_charge_path
    else
    @patient = Patient.new
  end
  end

  # GET /patients/1/edit
  def edit
    # @image = @patient.images.build
    @patient = Patient.find(params[:id])
    @image = Image.new
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
    @patient.user_id = current_user.id
    respond_to do |format|
      if @patient.save
        format.html { redirect_to edit_patient_path(@patient), notice: 'Patient Folder was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to root_path, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    if @patient.email.present?
      ImagesMailer.email(@patient).deliver_later
    end  
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient Folder was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :token, :email, :parent_id, :identifier, images_attributes: [:id, :description, :done, :_destroy, :patient_name, :patient_id, :image_desc, :dob, :image_file, :user_name, :token, :user_id, :recipient])
      # params.require(:patient).permit(:name, :token, :email) - commented out for above to accept nested deletions
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/charges/new.html.erb
<body class="subdued">
</br>

  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-body">
      <div><center><%= image_tag("black-blue_logo.png", width: '200', height: '75') %></center>

</p>
            <hr>

  <div>         
      <div style="text-align: center;">
        <h4>Thanks for trying us out!</h4>
        <p>Now help us keep the lights on..  Unlimited use of PatientPhotos.net is just $24.95 per month!

     </h4>
        <p style="padding-top: 10px;"> There’s <u>no risk</u> and you can cancel anytime with a single click from your dashboard.</p><br>
      </div><center>
      <%= form_tag charges_path do %>
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Dental Imager Subscription"
          data-amount="2495"
          ></script>
          <% end %></center>
  </div>   
  <hr> 
      <div>
          <center>Having trouble?<br>  Reach out to us at <a href="mailto:support@patientphotos.net">support@dentalimager.com</a></center>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</body>

app/views/images/_form.html.erb
<%= render 'sidebar' %>
<body style='padding-left: 15px;'>
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field">
    Image Description:<br>
    <%= f.text_field :image_desc %>
  </div>
  <div class="field">
    Patient DOB<sub><i> *required</i></sub><br>
    <%= f.text_field :dob %>
  </div>
  <div class="field">
  Your recipient's email address:<sub><i> *required</i></sub><br>
  <%= f.email_field :recipient %>
  </div>
    <div class="field">
  Your recipient's email address:<sub><i> *required</i></sub><br>
  <%= f.select :patient_id, options_from_collection_for_select(Patient.all, "id", "name")%>
  </div>
  <div class="filefield">
  Attach your image file:
  <%= f.file_field :image_file, multiple: true %>
  </div>
<br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<%= render 'form' %>

<h3>Click Image to Edit</h3>
<a href="javascript:pixlr.overlay.show({image:'<%= @image.image_file.url %>', title:'<%= @image.image_file_file_name %>', service:'editor', target:' http://b30c8245.ngrok.io/images/165>', exit:'http://localhost', referrer:'Dental Imager', locktarget:'true', locktitle:'true', quality:'100', locktype:'jpg', exit:'http://www.google.com'});" title='edit'> <%= image_tag @image.image_file %></a>



    // <script type="text/javascript">
    //     pixlr.settings.target = '<%= @image.image_file.url %>';
   	//  	pixlr.settings.exit = 'http://localhost';
   	// 	pixlr.settings.method = 'POST';
   	//     pixlr.settings.redirect = false;
    // </script>

app/views/images/index.html.erb
<%= render 'sidebar' %>
<body>
<div class="sign_out_right">
<%= button_to 'Sign Out', destroy_user_session_path,  :method=>'delete', :class => 'btn btn-large btn-black text-center'%>
</div>
<div class="left-pad">


</div>

app/views/images/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p class="header">
  <strong>Patient name:</strong>
  <%= @image.patient_name %>  |
    <strong>Secondary Identifier:</strong>
  <%= @image.patient_id %>   |

  <strong>Image description:</strong>
  <%= @image.image_desc %>   |

  <strong>Patient DOB:</strong>
  <%= @image.dob %>

</p>
<%= image_tag @image.image_file.url %>
<br>
<%= link_to "Download", @image.image_file.url(:original, false) %>

<br>
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PatientPhotos.net</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= yield %>

</body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
</html>

app/views/pages/index.html.erb
Index.html

app/views/patients/_form.html.erb
<center>
  <h4>Add Images to this Folder </h4>
<%= form_for Image.new, html: { multipart: true } do |f| %>
    <%= f.hidden_field :patient_id, value: @patient.id %>
  <div class="field">
    Image Description:<br>
    <%= f.text_field :image_desc %>
  </div>
  <div class="filefield">
  Attach your image file:
  <%= f.file_field :image_file %>
  </div>
<br>

  <div class="actions">
    <%= f.submit "Add This Image"  %>
  </div>

<% end %>
</div>

app/views/patients/_sidebar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand"><%= image_tag "logo.png", height: 25 %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
                <li><%= link_to "Patient Files", root_path %></li>
                                <li><%= link_to "Edit my Profile", edit_user_registration_path %></li>

        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to " Log Out", destroy_user_session_path,  :method=>'delete' %>
                </li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/patients/edit.html.erb
<%= render 'sidebar' %>

<div class="left-pad">
<br>
<h3><%= @patient.name %></h3>
<hr>
<h4>Images Currently Available:</h4>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Created at</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patient.images.each do |image| %>
      <tr>
        <td><%= image.created_at.strftime("%b %d %Y") %></td>
        <td><%= image.image_desc %></td>
        <!-- <td><%= link_to 'Edit', edit_image_path(image) %></td> -->
        <td><%= image_tag image.image_file(:thumb) %></td> 
        <% if user_signed_in? %>
        <td><%= link_to (image_tag("trash.png", width: '15', height: '15')) + " Delete Image", image, method: :delete, data: { confirm: 'Are you sure?' }  %></td>
        <% end %>

</tr>
    <% end %>
  </tbody>
</table>

<div class="row" >
  <div class="col-xs-6">




<!-- Button trigger modal --><center>
<button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#addimages">
  <span class="glyphicon glyphicon-floppy-open"></span> Add Images 
</button>
</center>
<!-- Modal -->
<div class="modal fade" id="addimages" tabindex="-1" role="dialog" aria-labelledby="addimages">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Images to this Folder</h4>
      </div>
      <div class="modal-body">
        <%= render 'form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>



<div class="col-xs-6">

<!-- Button trigger modal --><center>
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#share">
  <span class="glyphicon glyphicon-share"></span> Share Folder 
</button>
</center>



<!-- Modal -->
<div class="modal fade" id="share" tabindex="-1" role="dialog" aria-labelledby="share">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Share this patient's folder</h4>
      </div>
      <div class="modal-body">
<center>


        <%= form_for(@patient) do |f| %>
          <% if @image.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

              <ul>
              <% @image.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            Recipient's Email:<br>
            <%= f.email_field :email %>
          </div>
            <div class="actions">
            <%= f.submit "Share Patient Folder" %>
          </div>
          <% end %>
        </div>

</center>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>




</div>
<br>
<div class="center">
<%= link_to 'View Patient Images', @patient %> | <%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<%= render 'sidebar' %>

<div class="left-pad">
<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Patient Name</th>
      <th>Patient ID</th>
      <th>Created on</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>   &nbsp <%= patient.name %></td>
        <td><%= patient.identifier %></td>
        <td><%= patient.created_at.strftime("%B %d, %Y at %H:%M") %></td>
        <td><%= link_to 'View Slideshow', patient %></td>
        <!-- <td><%= link_to "Share", patient_share_path, :patient_id => patient.id, :patient_name => patient.name %></td> -->
        <td><%= link_to 'Add Files & Share Folder', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy Patient Folder', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="center">
<%= will_paginate @patient %>

<%= button_to '+ Create new patient folder', new_patient_path, :class => 'btn btn-large btn-success text-center', :method => :get  %>
<br>

app/views/patients/new.html.erb
<%= render 'sidebar' %>
<body style='padding-left: 15px;'>

<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
<h2>New Patient Folder</h2>

  <div class="field">
   <strong> Patient Name<br></strong>
    <%= f.text_field :name %>
  </div>

  <div class="field">
   <strong> Patient Identifier </strong><i>(DOB or Patient ID)</i><br>
    <%= f.text_field :identifier %>
  </div>

  <div class="actions">
    <%= f.submit "Create Patient Folder"%>
  </div>
<% end %>
<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
       <% @patient.images.each_with_index do |image, n|%>
         <li data-target='#MyCarousel' data-slide-to="#{n}" class="#{'active' if n == 0}"></li>
       <% end %>
    </ol>

    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= image_tag @patient.images.first.image_file.url %>
      </div>
      <% @patient.images.drop(1).each do |image| %>
         <div class="item">
           <%= image_tag image.image_file.url %>
         </div>
      <% end %>
    </div>

      <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<!-- TODO: need to somehow stop the carousel from moving on mobile device on it's own -->
<% if user_signed_in? %>
<div class="center">
<%= link_to 'Add Image Files', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>
<% end %>
</div>